version: '3'

services:
    hornbach-test-app:
        build:
            context: ./
            dockerfile: Dockerfile
        command: [ "php-fpm", "-F", "-R", "-dxdebug.mode=develop,debug" ]
        volumes:
            - ".:/var/www/hornbach-test-app:cached"
            - "~/.composer:/var/composer:cached"
